### ISSUE TITLE
bug: implement JSON Schema keyword *not*

### ISSUE THREAD

**Issue by schuur** [mill6-plat6aux/lupinus#1]
JSON Schema (and OpenAPI 3.1) define the following keywords to be used for composition of polymorph schemas (See https://json-schema.org/understanding-json-schema/reference/combining)

- oneOf
- anyOf
- allOf
- not

Support for the **not** keyword is currently missing. Pseudo code to be included around 630 in `validator.js`

>     if(schema.not != null) {
>         try {
>             this.validateJson(data, schema.not, key);
>         } catch {
>             // this is good. schema should not validate.
>         }
>         throw new Error("not validating: schema: ${schema}");
>     }

**Comment by mill6-plat6aux** [comment]
Thank you for reporting the bug!

It has been fixed in version `0.9.15`. Please check it out.
